---
- name: register rbd bootstrap key
  set_fact:
    bootstrap_rbd_keyring: "/var/lib/ceph/bootstrap-rbd/{{ cluster }}.keyring"
  when: ceph_release_num.{{ ceph_release }} >= ceph_release_num.luminous

- name: set config and keys paths
  set_fact:
    ceph_config_keys:
      - "{{ ceph_conf_key_directory }}/{{ cluster }}.client.admin.keyring"
      - "{{ ceph_conf_key_directory }}/{{ cluster }}.conf"
      - "{{ ceph_conf_key_directory }}/monmap-{{ cluster }}"
      - "{{ ceph_conf_key_directory }}/{{ cluster }}.mon.keyring"
      - /var/lib/ceph/bootstrap-osd/{{ cluster }}.keyring
      - /var/lib/ceph/bootstrap-rgw/{{ cluster }}.keyring
      - /var/lib/ceph/bootstrap-mds/{{ cluster }}.keyring
      - "{{ bootstrap_rbd_keyring | default([]) }}"

- name: stat for ceph config and keys
  stat:
    path: "{{ item }}"
  with_items: "{{ ceph_config_keys }}"
  changed_when: false
  failed_when: false
  always_run: true
  register: statleftover

- name: fail if we find existing cluster files
  fail:
    msg: "looks like no cluster is running but ceph files are present, please remove them"
  with_together:
    - "{{ ceph_config_keys }}"
    - "{{ statleftover.results }}"
  when: item.1.stat.exists == true
