---
- name: configure debian community repository
  include: debian_community_repository.yml
  when:
    - ceph_repository == 'community'

- name: configure debian rhcs repository
  include: debian_rhcs_repository.yml
  when:
    - ceph_repository == 'rhcs'

- name: configure debian dev repository
  include: debian_dev_repository.yml
  when:
    - ceph_repository == 'dev'

- name: configure debian custom repository
  include: debian_custom_repository.yml
  when:
    - ceph_repository == 'custom'

- name: configure debian cloud archive repository
  include: debian_uca_repository.yml
  when:
    - ceph_repository == 'uca'

