---
- name: configure redhat repository installation
  include: configure_redhat_repository_installation.yml
  when:
    - ceph_origin == 'repository'

- name: configure redhat local installation
  include: configure_redhat_local_installation.yml
  when:
    - ceph_origin == 'local'

- name: install redhat packages
  include: install_redhat_packages.yml
  when:
    - (ceph_origin == 'repository' or ceph_origin == 'distro')
